config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    if user.is? :admin
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end

      can :destroy, Comment do |comment|
        comment.author == user
      end
      can %i[read create], :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: :comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, counter_cache: :likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User', counter_cache: :posts_counter

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  def update_posts_counter
    user.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :jwt_authenticatable, jwt_revocation_strategy: self

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  ROLES = %i[admin default].freeze

  def recent_posts
    posts.limit(3).order(created_at: :desc)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    new_id = params[:post_id]
    @comments = Comment.where({ post_id: new_id }).order(:created_at)
    render json: { data: { comments: @comments } }, status: :ok
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_parameters[:text], author_id: current_user.id, post_id: @post.id)
    if @comment.save
      render json: @comment
    else
      render error: { error: 'Unable to create comments' }, status: 400
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.order(:created_at)
    render json: { data: { posts: @posts } }, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    @user = User.find(params[:id])
    render json: { success: true, data: { user: @user } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery prepend: true

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(text: comment_parameters[:text], author_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to user_post_path(@post.author_id, @post.id), notice: 'Comment saved successfully'
        else
          redirect_to user_post_path(@post.author_id, @post.id), alert: 'Error, Comment not created!'
        end
      end
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html do
        if @comment.destroy
          redirect_to user_post_path(@post.author_id, @post.id), notice: 'Comment deleted successfully'
        else
          redirect_to user_post_path(@post.author_id, @post.id), alert: 'Error, Comment not deleted!'
        end
      end
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @new_like = @post.likes.create(author_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @new_like.save
          redirect_to user_post_path(@post.author_id, @post.id), notice: 'Liked 👍'
        else
          redirect_to user_post_path(@post.author_id, @post.id), alert: 'Unable to like'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  skip_authorize_resource only: [:all_posts]

  def index
    @user = User.includes(:posts).find_by(id: params[:user_id])
    @posts = @user.recent_posts
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @post = @user.posts.includes(:comments, :likes).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      format.html do
        if @post.save
          redirect_to user_post_path(@post.author_id, @post.id), notice: 'Post has been successfully created!'
        else
          render :new, alert: 'Post not created. Please try again!'
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_posts_path(@post.author_id), notice: 'Post has been successfully deleted!'
    else
      redirect_to user_post_path(@post.user.id, @post.id), alert: 'Post not deleted. Please try again!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_img(user)
    user.photo.present? ? user.photo : 'http://www.pselaw.com/wp-content/uploads/2016/08/pokemon-150x150.jpg'
  end
end

app/views/comments/_comment_form.html.erb
 <%= form_with model:[@post, @post.comments.build], method: :post, local: true do |form| %>
   <%= form.label :text, "Post A Comment" %><br>
    <%= form.text_area :text, size:"60x5", required: true %><br>

    <%= form.submit "Add Comment", data: {disable_with: "Commenting..."}, class: "btn btn-primary" %>
 <% end %>

app/views/comments/_comments_section.html.erb
<div>
<% unless comments.empty? %>
  <ul class="all_comments">
    <% comments.each do |comment| %>
      <li class="d-flex justify-content-between align-items-center w-4 mx-auto">
        <h4><%= comment.author.name %>: <%= comment.text %></h4>
        <% if can? :destroy, comment %>
        <%= button_to "Delete", post_comment_path(comment.post_id, comment.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"%>
        <% end %>
      </li>
    <% end %>
</ul>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
    <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<%= form_with model:[@post, @post.likes.build] do |f|%>
    <%= f.submit "Like this post", data: {disable_with: "💖"}, class: "btn btn-success" %>
<%end%>

app/views/posts/_post_details.html.erb
  <%= link_to user_post_path(@user.id, post.id), id: "user_post#{post.id}" do %>
    <h2 class="post__title"><%= post.title %></h2>
  <% end %>
  <p class="post__text"><%= post.text.first(500) %>  </p>
  <div class="post__likes_comments_counter">
    <p class="show-li">Comments : <%= post.comments.size.to_i%>  Likes : <%= post.likes.size.to_i %> </p>
  </div>

app/views/posts/index.html.erb
<section>
  <nav class="nav">
    <div>
      <%= render "/users/back" %>
      <%= render "/users/home" %>
    </div>
    <%= link_to "New Post", new_user_post_path(@user.id) %>
  </nav>
  <div class="user_card">
  <%= render partial: "users/user_details", locals: { user: @user } %>
  </div>

  <div class="post_comments">
   <% @posts.each do |p| %>
   <ul class="all_posts posts">
   <li>
   <%= render partial: "post_details", locals: { post: p } %>
   </li>
   </ul>
   <%= render partial: "/comments/comments_section", locals: { comments: p.recent_comments } %>
   <% end %>
   </div>

   <button class="btn btn-1">Pagination</button>
</section>

app/views/posts/new.html.erb
<%= render "/users/back" %>
<section class="create-post">
  <h2>Create Post</h2>

  <%= form_with model: @post, url: user_posts_path, scope: :post, html: {class: "post-form"} do |form| %>
    <div class="title">
      <%= form.label :title, "Post Title" %>
      <%= form.text_field :title, placeholder: "Your Title...", required: true %>
    </div>

    <%= form.text_area :text, size: "100x20", placeholder: "Type your post here...", required: true %>

    <%= form.submit "Create Post", disable_with: "Please wait...", class: "post-btn" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<div>
  <%= link_to "Back", user_posts_path(@post.author.id) %>
  <%= render "/users/home" %>
  <div class="post">
    <div class="post_head">
        <h2 class="post__title"><%= @post.title %> by <%= @post.author.name %></h2>
      <div class="post__likes_comments_counter">
        <p class="show-li">Comments : <%= @post.comments.size%>  Likes : <%= @post.likes.size %> </p>
      </div>
    </div>
    <p class="post__text"><%= @post.text %> </p>
  </div>

    <%= render partial: "/comments/comments_section", locals: { comments: @post.comments } %>
    <%= render "/comments/comment_form" %>
    <%= render "/likes/like" %>
    <% if can? :destroy, @post %>
      <%= button_to "Delete", user_post_path(@post.author.id, @post.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"%>
    <% end %>
</div>

app/views/users/_back.html.erb
<%= link_to "Back", :back %>

app/views/users/_home.html.erb
<%= link_to "Home", authenticated_root_path %>

app/views/users/_user_details.html.erb

  <div class="user_details">
  <div  class="avatar">
    <%= image_tag user_img(user), alt: "User #{user.id} image" %>


  </div>
    <div class="user_list">
      <h2 class="user_name"><%= user.name %></h2>
      <p class="num_post">Number of posts: <%= user.posts.size %></p>
    </div>
  </div>

app/views/users/index.html.erb
<section class="user_card">
 <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
  <ul>
    <% @users.order(:created_at).each do |person| %>
    <li>
      <%= link_to user_path(person.id) do %>
       <%= render partial: "user_details", locals: {user: person} %>
      <% end %>
      <% end %>
    </li>
  </ul>
</section>

app/views/users/show.html.erb
<div>
<%= render "back" %>
  <div class="user_card">
    <%= render partial: "user_details", locals: { user: @user } %>
  </div>
  <div class="bio">
    <h2 class="bio_head">Bio</h2>
    <p class="bio_text"><%= @user.bio %> </p>
  </div>
  <ul class="all_posts">
    <% @user.recent_posts.each do |p| %>
      <li class="post">
        <%= render partial: "posts/post_details", locals: { post: p } %>
      </li>
    <% end %>
  </ul>
  <div class="actions">
    <%= link_to "See all posts", user_posts_path(@user.id), class: "see_all" %>
  <div>
</div>